
model:
  arch: blip_classification

  load_pretrained: True
  pretrained: "/home/Data/models/vit-large/pretrained-Vit_large-ImageNet_LT.pth"


  use_distill: True
  momentum: 0.995
  alpha: 0.4

  # vit encoder
  vit_type: "large"
  ## 设置成True以时间换空间，来节省gpu显存
  vit_grad_ckpt: False
  vit_ckpt_layer: 0

  image_size: 384

  num_classes: 1000
  cls_head: "tSP"
  criterion: "ce"

  # bert config
  med_config_path: "configs/models/med_large_config.json"


preprocess:
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 384
        eval:
          name: "blip_image_eval"
          image_size: 384
    text_processor:
        train:
          name: "blip_caption"
          prompt: ""
        eval:
          name: "blip_caption"

